### ISSUE TITLE
[functionality]ToDo:  Add save/load

### ISSUE THREAD

**Issue by Sillinde** [Sillinde/Sillinde.github.io#6]
It's another easy one.  I'm lazy, though.  I know how to do an autosave every 60 ticks, and how to automatically load.  I just haven't done it yet because I want more variables assigned so that I can add more at once to the save function.

**Comment by TheAntonverse** [comment]
How do you foresee saving? If we continue to use the dictionary data structure to hold our values (as seen in main.js with 'gains' and 'resources') then I think the 'json' format is what we use? I only have experience in Python using 'json' as a way to save/load these dictionary structures (I showed you a couple of saved files last time I visited from old game engines I wrote). I am not sure how it works in JavaScript, though, or where they need to be saved to since it's a browser game.

**Comment by Sillinde** [comment]
I was actually in the process of working on that.  XD  I'm gonna try something, here, which probably will just end up breaking something terribly.  D:

var save = {
    food: resources["food"],
    wood: resources["wood"],
    stone: resources["stone"]
}

and then:

localStorage.setItem("save",JSON.stringify(save));

**Comment by Sillinde** [comment]
Oh, and put that on a sort of timer, so it would run the localStorage bit every 60 ticks, or so.

**Comment by Sillinde** [comment]
Closing this.  savesandloads takes care of this.  Probably push that live tonight, and see what we get.

**Comment by Sillinde** [comment]
Wonderful.  Everything is actually working on my end, as well, tonight, instead of being stupid.  I'mma close this, since I guess I didn't close it before.
